[2019-11-03 13:00:13,803] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-92707119-16e0-49da-965f-76ca54cc1b8d in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:00:13,804] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 6 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-92707119-16e0-49da-965f-76ca54cc1b8d on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:00:15,542] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-2e4b0187-169e-4219-95d9-aa986fec5385 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:00:15,542] INFO [GroupCoordinator 0]: Stabilized group my-group generation 7 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:00:15,545] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 7 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:01:44,598] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 7 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-d42dc884-2666-4840-ae50-56937345e47a) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:01:45,936] INFO [GroupCoordinator 0]: Stabilized group my-group generation 8 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:01:45,938] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 8 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:01:57,584] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 13:02:35,601] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 8 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-3ec71b97-415a-4c17-8970-7ed9aa5e5175) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:02:35,754] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-d42dc884-2666-4840-ae50-56937345e47a in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:02:38,418] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-3f1fe25f-566c-49ed-8f72-b5c1ad6dd491 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:02:38,419] INFO [GroupCoordinator 0]: Stabilized group my-group generation 9 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:02:38,420] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 9 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:06:00,946] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-3ec71b97-415a-4c17-8970-7ed9aa5e5175 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:06:00,946] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 9 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-3ec71b97-415a-4c17-8970-7ed9aa5e5175 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:06:03,003] INFO [GroupCoordinator 0]: Stabilized group my-group generation 10 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:06:03,010] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 10 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:28,161] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-8de654c8-fc83-4f8a-b147-da18d28a4996 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:28,161] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 10 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-8de654c8-fc83-4f8a-b147-da18d28a4996 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:30,435] INFO [GroupCoordinator 0]: Stabilized group my-group generation 11 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:30,443] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 11 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:31,363] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 11 (__consumer_offsets-12) (reason: Updating metadata for member kafka-python-1.4.7-f49897c0-409f-41ad-91c9-ba9f7e148ed7) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:31,363] INFO [GroupCoordinator 0]: Stabilized group my-group generation 12 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:08:31,366] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 12 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:09:07,594] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 12 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-2d0093ce-fe1c-491f-a572-990a2ba2c26c) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:09:10,461] INFO [GroupCoordinator 0]: Stabilized group my-group generation 13 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:09:10,462] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 13 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:10:12,846] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 13 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-3afe8e3e-2246-406a-9bbb-08065f36bf54) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:10:14,501] INFO [GroupCoordinator 0]: Stabilized group my-group generation 14 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:10:14,512] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 14 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:12,855] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-3afe8e3e-2246-406a-9bbb-08065f36bf54 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:12,855] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 14 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-3afe8e3e-2246-406a-9bbb-08065f36bf54 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:14,526] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-2d0093ce-fe1c-491f-a572-990a2ba2c26c in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:15,033] INFO [GroupCoordinator 0]: Stabilized group my-group generation 15 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:15,038] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 15 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:16,244] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 15 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-14005341-cb9a-4433-9222-0ea7c97a9709) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:18,046] INFO [GroupCoordinator 0]: Stabilized group my-group generation 16 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:18,047] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 16 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:11:57,584] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 13:12:15,986] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 16 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-924636e7-a4d5-4a80-ac42-41e0acc22f38) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:12:18,901] INFO [GroupCoordinator 0]: Stabilized group my-group generation 17 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:12:18,904] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 17 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:14:30,478] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 17 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-3cc79858-74ac-4bc5-9900-490c10330332) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:14:32,535] INFO [GroupCoordinator 0]: Stabilized group my-group generation 18 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:14:32,539] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 18 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:17:30,457] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 18 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-52d74bfa-61aa-4dab-9319-744b3adecb6b) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:17:33,468] INFO [GroupCoordinator 0]: Stabilized group my-group generation 19 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:17:33,478] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 19 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:18:16,992] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 19 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-9ef9e393-ecd0-4869-9f61-92713da3933e) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:18:19,841] INFO [GroupCoordinator 0]: Stabilized group my-group generation 20 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:18:19,843] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 20 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:38,432] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-9ef9e393-ecd0-4869-9f61-92713da3933e in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:38,433] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 20 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-9ef9e393-ecd0-4869-9f61-92713da3933e on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:38,434] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-924636e7-a4d5-4a80-ac42-41e0acc22f38 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:38,434] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-52d74bfa-61aa-4dab-9319-744b3adecb6b in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:40,407] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-3cc79858-74ac-4bc5-9900-490c10330332 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:40,871] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-14005341-cb9a-4433-9222-0ea7c97a9709 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:40,871] INFO [GroupCoordinator 0]: Stabilized group my-group generation 21 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:40,873] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 21 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:55,648] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 21 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-0c0b5bde-eda4-428f-bbbc-41124c3225cf) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:55,925] INFO [GroupCoordinator 0]: Stabilized group my-group generation 22 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:19:55,926] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 22 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:20:16,394] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 22 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-9a821e60-bdb7-40f2-8f31-809d91a1a9e6) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:20:17,011] INFO [GroupCoordinator 0]: Stabilized group my-group generation 23 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:20:17,013] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 23 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:21:57,584] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 13:31:57,584] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 13:33:30,805] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-11-03 13:33:30,895] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-11-03 13:33:30,897] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-11-03 13:33:30,898] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-11-03 13:33:30,899] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-11-03 13:33:31,240] WARN Session 0x10000167a730002 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1145)
[2019-11-03 13:33:31,351] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 13:33:31,352] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 13:33:32,854] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:32,855] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:32,955] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 13:33:34,571] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:34,571] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:35,938] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:35,938] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:37,306] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:37,306] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:38,016] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-f49897c0-409f-41ad-91c9-ba9f7e148ed7 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:33:38,017] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 23 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-f49897c0-409f-41ad-91c9-ba9f7e148ed7 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:33:38,022] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-9a821e60-bdb7-40f2-8f31-809d91a1a9e6 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:33:38,820] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:38,820] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:40,052] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:40,052] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:40,112] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-0c0b5bde-eda4-428f-bbbc-41124c3225cf in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:33:40,112] INFO [GroupCoordinator 0]: Group my-group with generation 24 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 13:33:41,555] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:41,556] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:43,271] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:43,272] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:44,849] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:44,850] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:46,162] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:46,163] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:48,123] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:48,124] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:49,427] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:49,428] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:51,509] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:51,510] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:53,207] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:53,208] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:54,780] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:54,781] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:56,118] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:56,119] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:58,137] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:58,144] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:59,615] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:33:59,616] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:01,393] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:01,394] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:02,931] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:02,932] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:04,928] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:04,929] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:07,005] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:07,005] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:08,387] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:08,388] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:09,491] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:09,492] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:11,114] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:11,115] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:13,066] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:13,067] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:14,403] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:14,403] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:16,175] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:16,175] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:17,822] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:17,822] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:19,916] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:19,916] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:21,683] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:21,683] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:23,674] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:23,674] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:25,190] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:25,190] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:26,394] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:26,394] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:28,325] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:28,326] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:30,092] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:30,093] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:31,329] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:31,331] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:33,182] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:33,183] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:34,812] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:34,813] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:36,547] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:36,548] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:37,840] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:37,841] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:39,520] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:39,521] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:40,950] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:40,951] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:42,691] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:42,692] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:44,785] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:44,786] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:46,116] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:46,117] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:47,320] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:47,320] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:49,012] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:49,012] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:50,939] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:50,939] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:52,693] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:52,693] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:53,884] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:53,885] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:55,710] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:55,711] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:57,530] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:57,530] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:58,691] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:34:58,692] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:35:00,658] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 13:35:00,659] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
