[2019-11-03 19:02:40,375] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-53054bd4-7e7b-49e0-a808-dc412d39ee16 in group my-group has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:40,377] INFO [GroupCoordinator 0]: Stabilized group my-group generation 68 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:40,383] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 68 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:40,386] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 68 (__consumer_offsets-12) (reason: Updating metadata for member kafka-python-1.4.7-0f44f100-824b-4226-aa41-771afd9a8c17) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:43,409] INFO [GroupCoordinator 0]: Stabilized group my-group generation 69 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:43,411] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 69 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:02:43,706] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 69 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-bbc792a1-236d-4abc-911f-7d3303b7e56c) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:03:38,636] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-4f4aa034-4cbe-4443-bb3f-625e82cb42de in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:03:38,637] INFO [GroupCoordinator 0]: Stabilized group my-group generation 70 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:03:38,653] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 70 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:06:57,711] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 19:08:38,671] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-71871d7e-ce16-481b-be9d-e47d4156b62e in group my-group has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:38,672] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 70 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-71871d7e-ce16-481b-be9d-e47d4156b62e on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:40,869] INFO [GroupCoordinator 0]: Stabilized group my-group generation 71 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:40,874] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 71 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:45,909] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 71 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-0e5910b7-c74d-40e0-b7b2-d83af70f4f62) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:47,115] INFO [GroupCoordinator 0]: Stabilized group my-group generation 72 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:47,118] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 72 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:08:50,896] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 72 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-6c1f8d52-756f-466f-8654-e98f716addda) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:03,497] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-0e5910b7-c74d-40e0-b7b2-d83af70f4f62 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:03,498] INFO [GroupCoordinator 0]: Stabilized group my-group generation 73 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:03,503] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 73 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:03,784] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 73 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-15fc03a7-778d-4b32-8475-e41e95a7e308) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:28,778] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-6c1f8d52-756f-466f-8654-e98f716addda in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:28,779] INFO [GroupCoordinator 0]: Stabilized group my-group generation 74 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:28,783] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 74 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:09:31,038] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 74 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-9846b1f4-b426-4356-a6ae-3facfbf902f1) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:36,363] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-02fdd477-add3-4f27-a08e-5e4d2d13ea6c in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:36,364] INFO [GroupCoordinator 0]: Stabilized group my-group generation 75 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:36,369] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 75 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-5c2c5dbc-5489-4841-8239-854aa7aeb878 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 75 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-5c2c5dbc-5489-4841-8239-854aa7aeb878 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-d54d107f-0cc3-4a77-b554-68ebbafec7b6 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-a6122771-4dcd-4727-9813-033f1e0e2b3f in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-bbc792a1-236d-4abc-911f-7d3303b7e56c in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-c131c4a0-cdfb-4d20-8d8e-3054b8ee8086 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-15fc03a7-778d-4b32-8475-e41e95a7e308 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-f0b3ca4b-3a1f-44cf-b433-39f2e5c110f3 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-a75a4e0a-0e94-4998-a26d-80b8de9279f0 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-e68077aa-5d3e-46c5-9a04-fa7ed7273a71 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:46,364] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-9846b1f4-b426-4356-a6ae-3facfbf902f1 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:48,534] INFO [GroupCoordinator 0]: Stabilized group my-group generation 76 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:11:48,537] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 76 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:12:30,043] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 76 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-a27ef78a-807f-4ccd-af6e-bb08dbffb888) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:12:31,118] INFO [GroupCoordinator 0]: Stabilized group my-group generation 77 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:12:31,121] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 77 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:00,111] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 77 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-1bd48771-82ec-4704-a2f9-a88a6910a32f) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:01,901] INFO [GroupCoordinator 0]: Stabilized group my-group generation 78 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:01,904] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 78 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:10,043] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 78 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-19696370-fcb2-4948-9ba2-830ebbf21738) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:15,029] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-1bd48771-82ec-4704-a2f9-a88a6910a32f in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:15,035] INFO [GroupCoordinator 0]: Stabilized group my-group generation 79 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:15,046] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 79 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:20,044] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 79 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-b1b8997f-4c4d-4686-b76c-06d1d7be1d90) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:28,081] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-19696370-fcb2-4948-9ba2-830ebbf21738 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:28,082] INFO [GroupCoordinator 0]: Stabilized group my-group generation 80 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:28,086] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 80 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:29,400] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 80 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-244a6be1-503c-4f1b-bfe0-caf3232ae8d0) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:31,236] INFO [GroupCoordinator 0]: Stabilized group my-group generation 81 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:31,239] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 81 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:40,039] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 81 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-8876a9b5-2f35-4f1b-a936-2043fcb35625) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:59,382] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-244a6be1-503c-4f1b-bfe0-caf3232ae8d0 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:59,383] INFO [GroupCoordinator 0]: Stabilized group my-group generation 82 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:13:59,386] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 82 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:14:09,220] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 82 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-ed19fd69-ad7c-440a-b39b-cf1c5ea93035) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:39,800] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-5685ab4b-1e6b-477a-82e8-a772cd53640b in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:39,801] INFO [GroupCoordinator 0]: Stabilized group my-group generation 83 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:39,807] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 83 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,048] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 83 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-c973e3d9-6554-4717-8ef7-e8a662d4c249) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,801] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-baa04904-1683-475a-b010-5f5e95ca6a5d in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,801] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-8876a9b5-2f35-4f1b-a936-2043fcb35625 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,801] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-b1b8997f-4c4d-4686-b76c-06d1d7be1d90 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,801] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-da27fc6d-c060-4452-a73a-d60ed7ab12b1 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,801] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-ed19fd69-ad7c-440a-b39b-cf1c5ea93035 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,802] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-a27ef78a-807f-4ccd-af6e-bb08dbffb888 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:15:49,802] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-daa23374-c8ec-457e-8c02-dc167f153f42 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:16:57,711] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 19:17:47,487] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-0784fc43-0b0c-4ec8-bc7e-7095e2973cd8 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:17:47,487] INFO [GroupCoordinator 0]: Stabilized group my-group generation 84 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:17:47,491] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 84 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:17:47,776] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 84 (__consumer_offsets-12) (reason: Adding new member kafka-python-1.4.7-473b329a-e355-4c52-b850-9889c28c64fb) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:22:47,519] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-1ef32891-95ec-4d01-ab8b-bdfb0d68bf58 in group my-group has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:22:47,520] INFO [GroupCoordinator 0]: Stabilized group my-group generation 85 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:22:47,523] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 85 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:22:48,032] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 85 (__consumer_offsets-12) (reason: Updating metadata for member kafka-python-1.4.7-0f44f100-824b-4226-aa41-771afd9a8c17) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:24:00,888] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-228289fa-feb0-4404-a0a8-5ce5d1720b60 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:24:00,890] INFO [GroupCoordinator 0]: Stabilized group my-group generation 86 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:24:00,895] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 86 (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:26:57,711] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-11-03 19:28:15,262] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-11-03 19:28:15,274] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-11-03 19:28:15,300] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-11-03 19:28:15,301] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-11-03 19:28:15,766] WARN Session 0x100000426440000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1145)
[2019-11-03 19:28:15,881] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 19:28:15,882] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 19:28:15,882] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 19:28:15,882] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 19:28:17,767] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:17,767] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:17,868] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-11-03 19:28:19,316] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:19,317] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:21,254] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:21,254] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:22,209] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-7df82a76-e37d-4b88-9e3d-d0d76159512b in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:22,209] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 86 (__consumer_offsets-12) (reason: removing member kafka-python-1.4.7-7df82a76-e37d-4b88-9e3d-d0d76159512b on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:22,209] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-848027e3-023e-4918-ad0a-4f8a1aa51ef7 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,032] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-f2da4e35-edfa-46d2-8b72-f63cc03dd589 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,067] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-c973e3d9-6554-4717-8ef7-e8a662d4c249 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,221] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:23,222] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:23,296] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-79dcf928-ff10-48da-bfb0-6f05a4b28dc6 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,348] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-5c634104-7f55-403c-ab8a-02b8c1d6da5a in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,350] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-a289423a-62ab-48d4-8f2f-1660392d8594 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,407] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-9ce60234-a815-4236-8522-37e73cf5043f in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:23,434] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-0f44f100-824b-4226-aa41-771afd9a8c17 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:24,600] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-36176fa2-d807-40ad-bafc-89202381603d in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:24,638] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:24,639] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:24,849] INFO [GroupCoordinator 0]: Member kafka-python-1.4.7-473b329a-e355-4c52-b850-9889c28c64fb in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:24,849] INFO [GroupCoordinator 0]: Group my-group with generation 87 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2019-11-03 19:28:26,301] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:26,302] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:28,389] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:28,390] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:29,586] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:29,587] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:31,313] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:31,313] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:32,692] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:32,693] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:34,703] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:34,703] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:35,900] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:35,900] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:37,922] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:37,922] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:39,575] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:39,576] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:41,095] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:41,095] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:42,495] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:42,495] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:43,822] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:43,822] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:45,528] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:45,528] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:46,976] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:46,976] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:49,072] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:49,072] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:50,711] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:50,711] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:52,356] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:52,356] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:54,255] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:54,255] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:55,626] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:55,627] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:57,419] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:57,419] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:58,697] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:58,697] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:59,958] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:28:59,958] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:01,959] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:01,959] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:03,815] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:03,815] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:05,287] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:05,287] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:07,074] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:07,074] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:08,505] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:08,505] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:10,162] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:10,162] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:11,481] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:11,481] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:13,454] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:13,454] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:14,666] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:14,666] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:15,898] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:15,898] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:17,710] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:17,710] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:19,316] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:19,316] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:21,337] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:21,337] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:23,060] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:23,060] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:24,876] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:24,877] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:26,946] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:26,947] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:28,592] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:28,593] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:30,429] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:30,430] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:31,773] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:31,774] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:33,502] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:33,503] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:35,462] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:35,462] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:36,977] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:36,977] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:38,867] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:38,867] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:40,179] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:40,179] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:41,669] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:41,669] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:42,864] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:42,864] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:44,420] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-11-03 19:29:44,420] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
